### ISSUE TITLE
Does not wait for Google Optimize to load unless you already have a script to wait

### ISSUE THREAD

**Issue by dobesv** [hudovisk/react-optimize#8] opened 2019-10-02 20:07 UTC
Currently this check whether `window.dataLayer.hide.end` is set to decide whether to wait for google optimize to be ready.

However, this is only set if you have another script that waits for Google Optimize to be ready.  In our case we didn't have that script.  I wonder if checking whether `window.google_optimize` is set would be a better way to check if you need to wait.

**Comment by tlaak** [comment] 2019-11-04 12:38
None of the variants will get rendered if window.google_optimize has not been initialised. It does not seem to default to the first one as it probably should.

This seems to be the case when an ad / content blocker in the browser prevents it from loading (always fails) or it has not loaded yet in the browser (random failures).

Steps to reproduce: Set Firefox content blocking (`about:preferences#privacy`) to _Strict_, reload the page and none of the variants will render.

**Comment by dobesv** [comment] 2019-11-04 19:01
@tlaak is that issue related to the one I reported here?  Maybe you need a new bug report for that?

**Comment by tlaak** [comment] 2019-11-04 22:34
Yes, I suspect they are related. If `window.google_optimize` is never initialised, nothing will happen. To fix this I would possibly have to implement a function which will poll for the existence of `window.google_optimize` and renders a fallback if it doesn't happen in certain amount of time (say, 500ms).

**Comment by dobesv** [comment] 2019-11-04 22:41
Ah, indeed, it does not have a timeout on waiting for Google Optimize to load.

**Comment by dobesv** [comment] 2019-11-04 22:43
I add another issue for that, I think it's separate and might actually be more important than this one.

https://github.com/hudovisk/react-optimize/issues/9

**Comment by hudovisk** [comment] 2019-12-09 03:56
merged in [v2.2.0](https://github.com/hudovisk/react-optimize/releases/tag/v2.2.0). Thanks for the support!

**Closed by hudovisk** 2019-12-09 03:56 UTC
